const assert = require('assert');
const path = require('path');
let language = 'pl';
global.window = {};
global.document = {documentElement:{getAttribute:()=>language},readyState:'loading',addEventListener:()=>{}};
require(path.join(__dirname,'..','scripts','hot-x-render.js'));
const hot = global.window.BriefRoomsHotX;
assert(hot,'renderer API should be exposed');
const direct={category:'markets',label_pl:'RYNKI',label_en:'MARKETS',title_pl:'Bezpośredni post rynkowy',title_en:'Direct market post',comment_pl:'To jest wystarczająco długi komentarz do zweryfikowanego, bezpośredniego postu opublikowanego na platformie X.',comment_en:'This is a sufficiently long comment attached to a verified direct public post published on the X platform.',tweet_url:'https://twitter.com/example/status/123456789?utm_source=test'};
const pinned={category:'ai',label_pl:'AI',label_en:'AI',title_pl:'Suwerenność AI i Europa',title_en:'AI sovereignty and Europe',comment_pl:'Ręcznie przypięty temat redakcyjny prowadzi do bieżącej dyskusji i wymaga jawnych kontrolowanych pól bezpieczeństwa.',comment_en:'A manually pinned editorial topic leads to a current discussion and requires explicit controlled safety fields.',tweet_url:'',search_url:'https://x.com/search?q=AI%20sovereignty%20Europe&src=typed_query&f=live',editorial_pin:true,link_kind:'x_search'};
const genericSearch={...pinned,editorial_pin:false};
assert.strictEqual(hot.cleanXUrl(direct.tweet_url),'https://x.com/example/status/123456789');
assert.strictEqual(hot.isConcreteXPost(direct.tweet_url),true);
assert.strictEqual(hot.isEditorialSearch(pinned),true);
assert.strictEqual(hot.isEditorialSearch(genericSearch),false);
assert.strictEqual(hot.itemUrl(genericSearch),'');
const selected=hot.usableItems([direct,pinned,genericSearch]);
assert.strictEqual(selected.length,2);
assert.strictEqual(selected[0].editorial_pin,true);
assert.strictEqual(hot.labels().topicCta,'Zobacz dyskusję na X →');
language='en';
assert.strictEqual(hot.labels().topicType,'X topic search');
assert.strictEqual(hot.labels().topicCta,'View the discussion on X →');
console.log('Hot X renderer tests passed: controlled PL/EN editorial searches and direct posts.');
