(()=>{"use strict";
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const tabs=[...document.querySelectorAll("[data-tab]")];
tabs.forEach(btn=>btn.addEventListener("click",()=>{tabs.forEach(x=>x.classList.toggle("active",x===btn));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id==="tab-"+btn.dataset.tab))}));
function renderInstruments(items){const root=document.getElementById("instrument-list");if(!root)return;root.innerHTML='<div class="instrument-row head"><span>Instrument</span><span>Klasa</span><span>Tenor</span><span>Status</span></div>'+items.map(x=>'<div class="instrument-row"><b>'+esc(x.label)+'</b><span>'+esc(x.asset_class)+'</span><span>'+esc(x.tenor)+'</span><span class="pill">'+esc(x.status)+'</span></div>').join("")}
function renderDecisions(items){const root=document.getElementById("decision-list");if(!root)return;if(!items.length){root.innerHTML='<p class="muted">Brak zamrożonych decyzji BRsJEV. LAB nie pokazuje danych demonstracyjnych jako wyników.</p>';return}root.innerHTML=items.slice(0,8).map(x=>'<div class="decision"><span>'+esc(x.instrument)+' '+esc(x.tenor)+'</span><strong class="'+esc(String(x.action).toLowerCase())+'">'+esc(x.action)+'</strong><span>'+((Number(x.probability)*100).toFixed(0))+'%</span></div>').join("")}
function renderMetrics(m){const root=document.getElementById("metrics");if(!root)return;const cells=[["Decyzje",m.decision_count],["Resolved",m.resolved_count],["Brier",m.brier_score],["ECE",m.ece]];root.innerHTML=cells.map(([k,v])=>'<div class="metric"><small>'+k+'</small><b>'+(v===null||v===undefined?"—":esc(v))+'</b></div>').join("")}
async function load(){try{const r=await fetch("/data/investments/brsjev_lab_public.json?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("data");const d=await r.json();renderInstruments(d.instruments||[]);renderDecisions(d.decisions||[]);renderMetrics(d.metrics||{})}catch(_){renderInstruments([{label:"EUR/USD",asset_class:"FX",tenor:"1D",status:"LAB"},{label:"EUR/USD",asset_class:"FX",tenor:"1W",status:"LAB"},{label:"BTC/USD",asset_class:"Crypto",tenor:"1D",status:"LAB"},{label:"BTC/USD",asset_class:"Crypto",tenor:"1W",status:"LAB"},{label:"S&P 500",asset_class:"Index",tenor:"1D",status:"LAB"},{label:"XAU/USD",asset_class:"Commodity",tenor:"1D",status:"LAB"},{label:"Stock Trading",asset_class:"Equities",tenor:"Dynamic",status:"LAB"}]);renderDecisions([]);renderMetrics({})}}
load();
})();