(()=>{'use strict';
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=0)=>Number.isFinite(Number(v))?new Intl.NumberFormat('pl-PL',{maximumFractionDigits:d}).format(Number(v)):'—';
const pct=(v,d=1)=>Number.isFinite(Number(v))?num(Number(v)*100,d)+'%':'—';
const get=async u=>{const r=await fetch(u+'?lab='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()};
const chip=s=>'<span class="central-chip">'+esc(String(s||'—').replaceAll('_',' '))+'</span>';
async function strategy(){const root=document.querySelector('#central-strategy-lab');if(!root)return;try{const r=await get('/data/investments/research_lab_report.json');const statuses=r.status_counts||{};root.innerHTML='<article class="panel central-head"><header><div><h2>Autonomous Strategy Research</h2><p>Izolowany silnik generowania i walidacji kandydatów strategii. Centralny LAB tylko odczytuje jego kanoniczny raport.</p></div>'+chip(r.execution_loop_closed?'LOOP CLOSED':'CHECK LOOP')+'</header><div class="central-stats"><div><small>Cykl research</small><strong>'+num(r.cycle)+'</strong></div><div><small>Evidence cycle</small><strong>'+num(r.evidence_cycle)+'</strong></div><div><small>Kandydaci</small><strong>'+num(r.candidate_count)+'</strong></div><div><small>Promotion registry</small><strong>'+num((r.promotion_registry||[]).length)+'</strong></div></div><p class="central-note">Pipeline pozostaje niezależny: candidate → walk-forward → frozen holdout → regime → prospective shadow. Brak automatycznej promocji do produkcji.</p></article>';}catch(e){root.innerHTML='<div class="central-error">Strategy Research jest chwilowo niedostępny.</div>'}}
async function brace(){const root=document.querySelector('#central-brace-lab');if(!root)return;try{const r=await get('/data/public/brace_spx_platform_public.json');const f=r.frozen_track||{},a=r.adaptive_research||{},p=r.promotion_gate||{};root.innerHTML='<article class="panel central-head"><header><div><h2>BRACE-SPX</h2><p>Frozen G6 i Adaptive Research pozostają jednym odseparowanym pipeline’em S&P 500. Tutaj widzisz jego stan bez przenoszenia backendu.</p></div>'+chip(p.status)+'</header><div class="central-stats"><div><small>Frozen G6</small><strong>'+num(f.observations_collected)+' / '+num(f.warmup_required)+'</strong></div><div><small>Research cycles</small><strong>'+num(a.research_cycles)+'</strong></div><div><small>Challengery</small><strong>'+num(a.active_challengers)+'</strong></div><div><small>Prospective N</small><strong>'+num(a.initial_challenger_prospective_n)+'</strong></div></div><div class="central-actions"><a href="/pl/inwestycje/brace-spx-lab.html">Pełny widok BRACE-SPX</a></div></article>';}catch(e){root.innerHTML='<div class="central-error">BRACE-SPX jest chwilowo niedostępny.</div>'}}
function metric(m){if(!m||m.value==null)return'—';return m.unit==='fraction'?pct(m.value,1):m.unit==='percent'?num(m.value,2)+'%':num(m.value,3)}
function domainLink(x){if(x.id==='gse-v2-learning-lab')return '<a href="/pl/geopolityka.html">Otwórz w Geopolityce</a>';if(x.id==='eurusd-abc-live-shadow')return '<a href="/pl/inwestycje/daily-trading.html">Otwórz w Daily Trading</a>';return''}
async function registry(){const root=document.querySelector('#central-registry-lab');if(!root)return;try{const [r,e]=await Promise.all([get('/data/investments/experiment_registry.json'),get('/data/investments/experience_store_public.json')]);const rows=(r.experiments||[]).map(x=>'<tr><td><strong>'+esc(x.name)+'</strong><small>'+esc(x.family)+'</small></td><td>'+esc(x.category)+'</td><td>'+num(x.sample_count)+' / '+num(x.minimum_sample)+'</td><td>'+metric(x.primary_metric)+'</td><td>'+chip(x.status)+'</td><td>'+domainLink(x)+'</td></tr>').join('');const s=e.summary||{},overall=e.overall_evidence||{},tp=overall.trading_performance||{};
const engineRows=(e.engines||[]).map(x=>{const ev=x.evidence||{},perf=ev.trading_performance||{};return '<tr><td><strong>'+esc(x.label||x.engine)+'</strong><small>'+esc(x.engine)+'</small></td><td>'+num(x.experience_count)+'</td><td>'+num(x.settled_count)+'</td><td>'+num(x.pending_count)+'</td><td>'+num(ev.sample_size)+' / '+num(ev.minimum_sample)+'</td><td>'+pct(perf.hit_rate,1)+'</td><td>'+num(perf.profit_factor,2)+'</td><td>'+pct(perf.expectancy_return_fraction,2)+'</td><td>'+chip(ev.assessment)+'</td></tr>'}).join('');
const recent=(e.recent_experiences||[]).slice(0,12).map(x=>'<tr><td>'+esc(x.engine_label||x.engine)+'</td><td><strong>'+esc(x.instrument||'—')+'</strong></td><td>'+esc(x.action)+'</td><td>'+pct(x.confidence_fraction,1)+'</td><td>'+chip(x.status)+'</td><td>'+pct(x.return_fraction,2)+'</td><td>'+esc(x.exit_reason||'—')+'</td></tr>').join('');
root.innerHTML='<article class="panel central-head"><header><div><h2>Experiment Registry</h2><p>Jedno miejsce nadzoru. GSE v2 i EUR/USD A/B/C pozostają w swoich domenach; Registry pokazuje tylko ich kanoniczny status.</p></div>'+chip((r.experiments||[]).length+' EXPERIMENTS')+'</header><div class="central-table-wrap"><table class="central-table"><thead><tr><th>Eksperyment</th><th>Typ</th><th>Próba</th><th>Wynik</th><th>Status</th><th>Domena</th></tr></thead><tbody>'+rows+'</tbody></table></div></article>'+
'<article class="panel central-head"><header><div><h2>Experience Store</h2><p>Wspólna pamięć evidence z prospektywnych decyzji i późniejszych wyników. Tylko odczyt — bez writebacku, strojenia i wpływu na produkcję.</p></div>'+chip(s.assessment)+'</header><div class="central-stats"><div><small>Doświadczenia</small><strong>'+num(s.experience_count)+'</strong></div><div><small>Rozliczone</small><strong>'+num(s.settled_count)+'</strong></div><div><small>Oczekujące</small><strong>'+num(s.pending_count)+'</strong></div><div><small>Silniki</small><strong>'+num(s.engine_count)+'</strong></div><div><small>Źródła</small><strong>'+num(s.source_count)+'</strong></div><div><small>Formal alpha</small><strong>'+esc(s.formal_alpha_status)+'</strong></div></div>'+
'<h3 class="central-subtitle">Evidence ogółem</h3><div class="central-stats"><div><small>Próba evidence</small><strong>'+num(overall.sample_size)+' / '+num(overall.minimum_sample)+'</strong></div><div><small>Hit rate</small><strong>'+pct(tp.hit_rate,1)+'</strong></div><div><small>Profit factor</small><strong>'+num(tp.profit_factor,2)+'</strong></div><div><small>Expectancy / trade</small><strong>'+pct(tp.expectancy_return_fraction,2)+'</strong></div><div><small>Max drawdown</small><strong>'+pct(tp.max_drawdown_fraction,1)+'</strong></div><div><small>Sharpe / trade</small><strong>'+num(tp.sharpe_per_trade,2)+'</strong></div></div>'+
'<h3 class="central-subtitle">Evidence per silnik</h3><div class="central-table-wrap"><table class="central-table"><thead><tr><th>Silnik</th><th>Dośw.</th><th>Rozl.</th><th>Pending</th><th>Próba</th><th>Hit rate</th><th>PF</th><th>Expectancy</th><th>Ocena</th></tr></thead><tbody>'+engineRows+'</tbody></table></div>'+
'<h3 class="central-subtitle">Ostatnie doświadczenia</h3><div class="central-table-wrap"><table class="central-table"><thead><tr><th>Silnik</th><th>Instrument</th><th>Akcja</th><th>Confidence</th><th>Status</th><th>Zwrot</th><th>Wyjście</th></tr></thead><tbody>'+recent+'</tbody></table></div>'+
'<p class="central-note">Źródła: '+esc((e.sources||[]).map(x=>x.label).join(' · '))+' · wygenerowano '+esc(e.generated_at||'—')+'. Publiczny widok nie eksponuje surowych payloadów, ledger paths ani signal snapshots.</p></article>';}catch(e){root.innerHTML='<div class="central-error">Registry / Experience Store są chwilowo niedostępne.</div>'}}
function start(){strategy();brace();registry()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();})();