(function(){
'use strict';
function lang(){var l=(document.documentElement.getAttribute('lang')||'').toLowerCase();return l.indexOf('en')===0||location.pathname.indexOf('/en/')===0?'en':'pl'}
function isHome(){var p=location.pathname.replace(/\/index\.html$/,'/');return p==='/'||p==='/pl/'||p==='/en/'}
function esc(s){return String(s||'').replace(/[&<>"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]})}
function addStyle(){if(document.getElementById('br-hot-x-fix'))return;var s=document.createElement('style');s.id='br-hot-x-fix';s.textContent='.source-feed{display:grid!important;gap:14px!important}.source-card.hot-tweet{display:block!important;overflow:hidden!important;padding:16px!important;border-radius:20px!important}.source-card.hot-tweet .tweet-img{height:118px!important;margin:-4px -4px 12px!important;border-radius:15px!important;overflow:hidden!important;background:rgba(255,255,255,.05)!important}.source-card.hot-tweet .tweet-img img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}.source-card.hot-tweet .tweet-kicker{display:inline-flex!important;margin-bottom:10px!important;border-radius:999px!important;padding:5px 9px!important;background:rgba(56,214,201,.12)!important;border:1px solid rgba(56,214,201,.22)!important;color:#8ffff6!important;font-size:10px!important;font-weight:950!important}.source-card.hot-tweet h3{margin:0 0 8px!important;font-size:18px!important;line-height:1.15!important}.source-card.hot-tweet p{margin:0 0 10px!important;font-size:13px!important;line-height:1.45!important;color:#c8d7e5!important}.source-card.hot-tweet span{color:#38d6c9!important;font-weight:950!important;font-size:13px!important}.brs-home-mark{display:inline-flex!important;align-items:center!important;justify-content:center!important;width:36px!important;height:32px!important;border-radius:11px!important;color:#08111d!important;background:linear-gradient(135deg,#f8c97a,#fff1c7 58%,#38d6c9)!important;font-size:14px!important;font-weight:950!important;letter-spacing:-.08em!important}.brs-home-name{font-size:26px!important;font-weight:950!important;color:#eef7ff!important}.brand .logo.brs-wordmark{display:inline-flex!important;align-items:center!important;gap:10px!important}';document.head.appendChild(s)}
function brand(){if(!isHome())return;var logo=document.querySelector('header.top .brand .logo');if(!logo||logo.dataset.brsReady)return;logo.classList.add('brs-wordmark');logo.innerHTML='<span class="brs-home-mark">BRs</span><span class="brs-home-name">BriefRooms</span>';logo.dataset.brsReady='1'}
function hot(){var feed=document.querySelector('.side .source-feed');if(!feed)return;addStyle();fetch('/data/hot_tweets.json?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{items:[]}}).then(function(data){var l=lang();feed.innerHTML=(data.items||[]).map(function(item){var title=item['title_'+l]||item.title_en||item.title_pl||'';var sum=item['summary_'+l]||item.summary_en||item.summary_pl||'';var label=item['label_'+l]||item.label_en||item.label_pl||'';var url=item.tweet_url||item.search_url||'https://x.com/explore';var img=item.image?'<div class="tweet-img"><img src="'+esc(item.image)+'" alt="" loading="lazy" referrerpolicy="no-referrer"></div>':'';return '<a class="source-card hot-tweet" href="'+esc(url)+'" target="_blank" rel="noopener">'+img+'<div class="tweet-kicker">'+esc(label)+'</div><h3>'+esc(title)+'</h3><p>'+esc(sum)+'</p><span>'+(l==='en'?'Open on X →':'Otwórz na X →')+'</span></a>'}).join('')})}
function init(){brand();hot()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();