(function(){
'use strict';
function lang(){var l=(document.documentElement.getAttribute('lang')||'').toLowerCase();return l.indexOf('en')===0||location.pathname.indexOf('/en/')===0?'en':'pl'}
function isHome(){var p=location.pathname.replace(/\/index\.html$/,'/');return p==='/'||p==='/pl/'||p==='/en/'}
function esc(s){return String(s||'').replace(/[&<>"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]})}
function style(id,css){if(document.getElementById(id))return;var e=document.createElement('style');e.id=id;e.textContent=css;document.head.appendChild(e)}
function homeBrand(){if(!isHome())return;var logo=document.querySelector('header.top .brand .logo');if(!logo||logo.dataset.brsReady)return;style('brs-home-wordmark-style','.brand .logo.brs-wordmark{display:inline-flex!important;align-items:center!important;gap:10px!important;white-space:nowrap!important}.brs-home-mark{display:inline-flex!important;align-items:center!important;justify-content:center!important;width:36px!important;height:32px!important;border-radius:11px!important;color:#08111d!important;background:linear-gradient(135deg,#f8c97a,#fff1c7 58%,#38d6c9)!important;border:1px solid rgba(255,255,255,.26)!important;box-shadow:0 10px 24px rgba(0,0,0,.24),inset 0 1px 0 rgba(255,255,255,.35)!important;font-size:14px!important;font-weight:950!important;letter-spacing:-.08em!important}.brs-home-name{font-size:26px!important;font-weight:950!important;letter-spacing:-.04em!important;color:#eef7ff!important}');logo.classList.add('brs-wordmark');logo.innerHTML='<span class="brs-home-mark">BRs</span><span class="brs-home-name">BriefRooms</span>';logo.dataset.brsReady='1'}
function aiBadge(){style('br-glass-ai-badge-style','.brand{align-items:flex-start!important;gap:9px!important}.ai-badge{display:inline-flex!important;align-items:center!important;gap:5px!important;margin-top:-4px!important;padding:4px 7px!important;min-height:22px!important;border-radius:999px!important;color:rgba(218,255,250,.92)!important;font-size:8.5px!important;font-weight:720!important;border:1px solid rgba(255,255,255,.16)!important;background:linear-gradient(180deg,rgba(255,255,255,.18),rgba(255,255,255,.05)),rgba(10,24,36,.28)!important;backdrop-filter:blur(16px) saturate(165%)!important}.ai-dot{width:5px!important;height:5px!important;border-radius:50%!important;background:#2bdacb!important}');}
function cleanText(t){t=String(t||'').replace(/Â£/g,'£').replace(/Â/g,'').replace(/â|â€”/g,'–').replace(/â/g,"'").replace(/â|â/g,'"');var markers=['TV Weather Sounds...','TV Weather Sounds…','TV Weather Sounds'];for(var i=0;i<markers.length;i++){var n=t.indexOf(markers[i]);if(n>=0){t=t.slice(n+markers[i].length);break}}['Home News Sport Earth Reel Worklife Travel Culture Future Music','More menu','Search BBC','Image source,','Image caption,','external'].forEach(function(x){t=t.split(x).join(' ')});return t.replace(/\s+/g,' ').trim()}
function shortComment(txt,title){var s=cleanText(txt);var parts=(s.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).map(function(x){return cleanText(x)}).filter(function(x){var y=x.toLowerCase();return x.length>35&&y.indexOf('accessibility')<0&&y.indexOf('homepage')<0&&y.indexOf('worklife')<0&&y.indexOf('search bbc')<0});var out=parts.slice(0,2).join(' ');if(!out&&title)out='This article is about: '+title.replace(/\.$/,'')+'.';if(out.length>260)out=out.slice(0,260).replace(/\s+\S*$/,'…');return out}
function cleanCards(){if(lang()!=='en'||!isHome())return;document.querySelectorAll('.brief-card').forEach(function(c){var p=c.querySelector('.brief-desc'),h=c.querySelector('.brief-title');if(!p||p.dataset.cleaned)return;var o=shortComment(p.textContent,h?h.textContent:'');if(o){p.textContent=o;p.dataset.cleaned='1'}})}
function watchCards(){if(lang()!=='en'||!isHome())return;cleanCards();var box=document.getElementById('latest-briefs');if(box){new MutationObserver(cleanCards).observe(box,{childList:true,subtree:true})}setTimeout(cleanCards,800);setTimeout(cleanCards,1800)}
function hotTweets(){var feed=document.querySelector('.side .source-feed');if(!feed)return;fetch('/data/hot_tweets.json?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{items:[]}}).then(function(data){var l=lang(),rows=data.items||[];feed.innerHTML=rows.map(function(item){var label=item['label_'+l]||item.label_en||item.label_pl||item.category||'';var title=item['title_'+l]||item.title_en||item.title_pl||'';var sum=item['summary_'+l]||item.summary_en||item.summary_pl||'';var url=item.tweet_url||item.search_url||'https://x.com/explore';var img=item.image?'<div class="tweet-img"><img src="'+esc(item.image)+'" alt="" loading="lazy" referrerpolicy="no-referrer"></div>':'';return '<a class="source-card hot-tweet" href="'+esc(url)+'" target="_blank" rel="noopener">'+img+'<div class="tweet-kicker">'+esc(label)+'</div><h3>'+esc(title)+'</h3><p>'+esc(sum)+'</p><span>'+(l==='en'?'Open on X →':'Otwórz na X →')+'</span></a>'}).join('')})}
function ticker(){var track=document.getElementById('br-hotbar-track');if(!track)return;var items=lang()==='en'?[['Latest news briefs','/en/news.html'],['Open the News room for current updates','/en/news.html']]:[['Najnowsze aktualności i krótkie briefy','/pl/aktualnosci.html'],['Kliknij Aktualności, aby zobaczyć bieżące podsumowania','/pl/aktualnosci.html']];track.innerHTML='';items.concat(items).forEach(function(it){var a=document.createElement('a');a.className='br-hotbar-item';a.href=it[1];a.textContent=it[0];track.appendChild(a);var s=document.createElement('span');s.className='br-hotbar-sep';s.textContent=' • ';track.appendChild(s)});track.classList.add('is-ready')}
function init(){homeBrand();aiBadge();hotTweets();ticker();watchCards()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();